services:
  apache:
    image: httpd:{{version}}
    container_name: panel_apache
    restart: unless-stopped
    ports:
      - "{{http_port}}:80"
      - "{{https_port}}:443"
    volumes:
      - /www/wwwroot:/www/wwwroot
      - /www/server/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - /www/server/apache/vhosts:/usr/local/apache2/conf/vhosts
      - /www/logs/apache:/usr/local/apache2/logs
      - /www/server/apache/ssl:/usr/local/apache2/conf/ssl
    networks:
      - panel_network

networks:
  panel_network:
    external: true
    name: panel_network
