services:
  phpmyadmin:
    image: phpmyadmin:{{version}}
    container_name: panel_phpmyadmin
    restart: unless-stopped
    ports:
      - "{{port}}:80"
    environment:
      PMA_HOST: "{{pma_host}}"
      PMA_PORT: 3306
      UPLOAD_LIMIT: 256M
    volumes:
      - /www/server/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    networks:
      - panel_network

networks:
  panel_network:
    external: true
    name: panel_network
