services:
  apache:
    image: httpd:{{version}}
    container_name: panel_apache
    restart: unless-stopped
    network_mode: host
    volumes:
      - /www/wwwroot:/www/wwwroot
      - /www/server/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - /www/server/apache/vhosts:/usr/local/apache2/conf/vhosts
      - /www/logs/apache:/usr/local/apache2/logs
      - /www/wwwlogs:/www/wwwlogs
      - /www/server/apache/ssl:/usr/local/apache2/conf/ssl
