services:
  apache:
    image: httpd:{{tag}}
    container_name: panel_apache
    restart: unless-stopped
    network_mode: host
    volumes:
      - /www/wwwroot:/www/wwwroot
      - /www/server/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - /www/server/apache/conf/vhost:/usr/local/apache2/conf/vhost
      - /www/logs/apache:/usr/local/apache2/logs
      - /www/wwwlogs:/www/wwwlogs
      - /www/server/apache/ssl:/usr/local/apache2/conf/ssl
      - /www/ssl:/www/ssl:ro
    deploy:
      resources:
        limits:
          memory: {{mem_limit}}
          cpus: "{{cpu_limit}}"
        reservations:
          memory: {{mem_reserve}}
