services:
  php:
    image: jzpanel/php:{{tag}}
    container_name: panel_php_83
    restart: unless-stopped
    network_mode: host
    volumes:
      - /www/wwwroot:/www/wwwroot
      - /www/server/php_83/php.ini:/usr/local/etc/php/php.ini:ro
      - /www/server/php_83/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - /www/logs/php_83:/var/log/php-fpm
    deploy:
      resources:
        limits:
          memory: {{mem_limit}}
          cpus: "{{cpu_limit}}"
        reservations:
          memory: {{mem_reserve}}
